### PR TITLE
Fixed issue #14 caused by xib files not being assigned as resource files

### PR DESCRIPTION
**Pull request by petersth**
xib files are incorrectly included as sources files which causes the error:

Unable to run command 'StripNIB CollapseClickCell.nib' - this target might include its own product.

### CODE REVIEW

**Comment by zdennis** [comment]
Thank you @petersth and @bennyguitar !

**Comment by bennyguitar** [comment]
@petersth did you push to the main CocoaPods repo too, or should I do that right now?

**Comment by petersth** [comment]
@bennyguitar I haven't pushed to the main repo.

**Comment by bennyguitar** [comment]
Okay, I'll go ahead and do that. Thanks for the fix.

**Pull request merged**
